- name: disable old module and enable nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: install nodejs -y
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app